# Generated by Django 4.1.7 on 2023-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-11-27'),
            preserve_default=False,
        ),
    ]
